clusterlist:
  - cluster: osdmgmtdrprd01
    url: 'https://kubernetes.default.svc'

destination:
   namespace: amq-streams

project: default

repoURL: https://github.com/Ankur7890/automation.git

paths:
 - int: https://github.com/Ankur7890/automation/amqstreams/overlays/int
 - app: https://github.com/Ankur7890/automation/amqstreams/overlays/aap
