apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: amq-streams-prod
  namespace: amq-streams
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  kafka:
    storage:
      type: jbod
      volumes:
      - deleteClaim: false
        id: 0
        size: 15Gi
        type: persistent-claim
