apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: amq-streams-prod
  namespace: amq-streams
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  kafka:
    listeners:
    - name: plain
      port: 9092
      tls: false
      type: internal
    - name: tls
      port: 9093
      tls: true
      type: internal
    - name: external
      port: 9094
      tls: true
      type: route
      configuration:
        bootstrap:
          labels: 
            type: sharded
        brokers:
        - broker: 0
          labels: 
            type: sharded
        - broker: 1
          labels: 
            type: sharded 
        - broker: 2
          labels: 
            type: sharded
 
