apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: amq-streams-prod
  namespace: amq-streams
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  kafka:
    listeners:
    - name: external
      port: 9094
      tls: true
      type: route
      configuration:
        bootstrap:
          host: bootstrap.myrouter.com
        brokers:
        - broker: 0
          host: broker-0.myrouter.com
        - broker: 1
          host: broker-1.myrouter.com
        - broker: 2
          host: broker-2.myrouter.com
 
