---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-redis-storage
  namespace: 3scale
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-storage
  namespace: 3scale
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: system-redis-storage
  namespace: 3scale
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: system-storage
  namespace: 3scale
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem



