apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: amq-broker-prod
  namespace: amq-broker
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acceptors:
  - anycastPrefix: jms.queue.
    enabledProtocols: TLSv1,TLSv1.1,TLSv1.2
    expose: true
    multicastPrefix: /topic/
    name: amqp
    port: 5672
    protocols: amqp
    sslEnabled: true
    sslSecret: my-tls-secret
  adminPassword: ProdAdmin@123
  adminUser: admin
  connectors:
  - enabledProtocols: TLSv1,TLSv1.1,TLSv1.2
    expose: false
    host: localhost
    name: connector0
    needClientAuth: true
    port: 22222
    sniHost: localhost
    sslEnabled: false
    sslProvider: JDK
    verifyHost: true
    wantClientAuth: true
  console:
    expose: true
    sslEnabled: true
    sslSecret: my-tls-secret-console
  deploymentPlan:
    image: placeholder
    jolokiaAgentEnabled: false
    journalType: nio
    managementRBACEnabled: true
    messageMigration: true
    persistenceEnabled: true
    requireLogin: true
    resources:
      limits:
        cpu: 1000m
        memory: 2048Mi
      requests:
        cpu: 500m
        memory: 1024Mi
    size: 2
    storage:
      size: 400Gi
  upgrades:
    enabled: false
    minor: false
