apiVersion: batch/v1
kind: Job
metadata:
  name: cert-gen-int
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "1"
spec: {}
