apiVersion: v1
kind: ServiceAccount
metadata:
  name: amq-broker-token
  namespace: amq-broker
  annotations:
    argocd.argoproj.io/sync-wave: "0"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: podview
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    kubectl.kubernetes.io/last-applied-configuration: ""
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podview
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "0"
   # kubectl.kubernetes.io/last-applied-configuration: ""
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: podview
subjects:
- kind: ServiceAccount
  name: login-token
  namespace: test

---


apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-sa-perm
  namespace: amq-broker
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    kubectl.kubernetes.io/last-applied-configuration: ""
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
  - create

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-sa-perm
  namespace: amq-broker
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    #kubectl.kubernetes.io/last-applied-configuration: ""
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-sa-perm
subjects:
- kind: ServiceAccount
  name: login-token
  namespace: test

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scc-anyuid
  namespace: amq-broker
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    kubectl.kubernetes.io/last-applied-configuration: ""
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa-to-scc-anyuid
  namespace: amq-broker
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    #kubectl.kubernetes.io/last-applied-configuration: ""
subjects:
  - kind: ServiceAccount
    name: amq-broker-token
roleRef:
  kind: Role
  name: scc-anyuid
  apiGroup: rbac.authorization.k8s.io
