apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-logging-applicationset
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
          - cluster: osdmgmtdrprd01
            url: 'https://kubernetes.default.svc'
          - cluster: osdintdrprd01
            url: 'https://api.osdintdrprd01.7sxv.p2.openshiftapps.com:6443'
          - cluster: osdappdrprd01
            url: 'https://api.osdappdrprd01.z6t6.p2.openshiftapps.com:6443'
  template:
    metadata:
      name: '{{cluster}}-logging'
    spec:
      destination:
        namespace: cluster-logging
        server: '{{url}}'
      project: default
      source:
        path: cluster-logging
        repoURL: 'https://github.com/OSD-INFRA-GITOPSDR/clusteroperators.git'
        targetRevision: main
      ignoreDifferences:
      - kind: Namespace
        jsonPointers:
        - /metadata/labels
        - /metadata/annotations
      syncPolicy:
        syncOptions:
          - ApplyOutOfSyncOnly=true
