apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: streams-as
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
          - cluster: {{ .Values.clusterlist.cluster }}
            url: '{{ .Values.clusterlist.url }}'
  template:
    metadata:
      name: '{{ .Values.clusterlist.cluster }}-logging'
    spec:
      destination:
        namespace: {{ .Values.destination.namespace }}
        server: '{{ .Values.clusterlist.url }}'
      project: {{ .Values.project }}
      source:
        path: {{ .Values.paths.int }}
        repoURL: {{ .Values.repoURL }}
        targetRevision: main
      syncPolicy:
        syncOptions:
          - ApplyOutOfSyncOnly=true
