apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance"
  namespace: "openshift-logging"
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  managementState: "Managed"
  logStore:
    type: "elasticsearch"
    retentionPolicy:
      application:
        maxAge: 10d
      infra:
        maxAge: 10d
      audit:
        maxAge: 10d
    elasticsearch:
      nodeCount: 3
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      resources:
        limits:
          cpu: 500m
          memory: 4Gi
        requests:
          cpu: 500m
          memory: 2Gi
      storage:
        storageClassName: "ocs-external-storagecluster-ceph-rbd"
        size: 10Gi
      redundancyPolicy: "SingleRedundancy"
  visualization:
    type: "kibana"
    kibana:
      replicas: 1
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 1Gi
  collection:
    type: vector

